/* --------------------------------------------------------------------------------- */
/* Host     : localhost                                                              */
/* Database : DATABASE.FDB */


CREATE DATABASE 'C:\DATABASE.FDB'
   USER 'SYSDBA'
   PASSWORD 'masterkey'
   PAGE_SIZE 8192
   DEFAULT CHARACTER SET WIN1252;

/* Definition for the `GEN_ID_ABASTECIMENTO` generator :  */

CREATE GENERATOR GEN_ID_ABASTECIMENTO;

/* Definition for the `GEN_ID_BOMBA` generator :  */

CREATE GENERATOR GEN_ID_BOMBA;

/* Definition for the `GEN_ID_FUNCIONARIO` generator :  */

CREATE GENERATOR GEN_ID_FUNCIONARIO;

/* Definition for the `GEN_ID_TANQUE` generator :  */

CREATE GENERATOR GEN_ID_TANQUE;

/* Structure for the `TBTANQUE` table :  */

CREATE TABLE TBTANQUE (
  ID INTEGER NOT NULL,
  NUMERO VARCHAR(15) CHARACTER SET NONE NOT NULL,
  TIPO_COMBUSTIVEL VARCHAR(30) CHARACTER SET NONE NOT NULL,
  CAPACIDADE_LITROS DECIMAL(15, 2) DEFAULT 0 NOT NULL,
  STATUS CHAR(1) CHARACTER SET WIN1252 DEFAULT 'S' NOT NULL COLLATE WIN1252);


ALTER TABLE TBTANQUE ADD CONSTRAINT TBTANQUE_PK PRIMARY KEY (ID);


/* Structure for the `TBBOMBA` table :  */

CREATE TABLE TBBOMBA (
  ID INTEGER NOT NULL,
  NUMERO VARCHAR(15) CHARACTER SET NONE NOT NULL,
  TANQUE_ID INTEGER NOT NULL,
  PRECO_LITRO DECIMAL(15, 2) DEFAULT 0 NOT NULL,
  STATUS CHAR(1) CHARACTER SET WIN1252 DEFAULT 'S' NOT NULL COLLATE WIN1252);


ALTER TABLE TBBOMBA ADD CONSTRAINT TBBOMBA_PK PRIMARY KEY (ID);

ALTER TABLE TBBOMBA ADD CONSTRAINT TBBOMBA_TBTANQUE_FK FOREIGN KEY (TANQUE_ID) REFERENCES TBTANQUE(ID);


/* Structure for the `TBFUNCIONARIO` table :  */

CREATE TABLE TBFUNCIONARIO (
  ID INTEGER NOT NULL,
  NOME VARCHAR(120) CHARACTER SET NONE NOT NULL,
  STATUS CHAR(1) CHARACTER SET WIN1252 DEFAULT 'S' NOT NULL COLLATE WIN1252);


ALTER TABLE TBFUNCIONARIO ADD CONSTRAINT TBFUNCIONARIO_PK PRIMARY KEY (ID);


/* Structure for the `TBABASTECIMENTO` table :  */

CREATE TABLE TBABASTECIMENTO (
  ID INTEGER NOT NULL,
  DATA_ABASTECIMENTO DATE NOT NULL,
  FRENTISTA_ID INTEGER NOT NULL,
  BOMBA_ID INTEGER NOT NULL,
  QUANT_TOTAL_LITROS INTEGER DEFAULT 0 NOT NULL,
  PERC_IMPOSTO DECIMAL(15, 2) DEFAULT 0 NOT NULL,
  RS_TOTAL_BRUTO DECIMAL(15, 2) DEFAULT 0 NOT NULL,
  RS_TOTAL_LIQUIDO DECIMAL(15, 2) DEFAULT 0 NOT NULL,
  STATUS CHAR(1) CHARACTER SET WIN1252 DEFAULT 'S' COLLATE WIN1252);


ALTER TABLE TBABASTECIMENTO ADD CONSTRAINT TBABASTECIMENTO_PK PRIMARY KEY (ID);

ALTER TABLE TBABASTECIMENTO ADD CONSTRAINT TBABAST_TBBOMBA_FK FOREIGN KEY (BOMBA_ID) REFERENCES TBBOMBA(ID);

ALTER TABLE TBABASTECIMENTO ADD CONSTRAINT TBABAST_TBFUNC_FK FOREIGN KEY (FRENTISTA_ID) REFERENCES TBFUNCIONARIO(ID);


/* Structure for the `TBCONFIG` table :  */

CREATE TABLE TBCONFIG (
  ID INTEGER NOT NULL,
  PERC_IMPOSTO DECIMAL(15, 2) DEFAULT 0 NOT NULL);


ALTER TABLE TBCONFIG ADD CONSTRAINT TBCONFIG_PK PRIMARY KEY (ID);


/* Definition for the `TG_ABASTECIMENTO` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TG_ABASTECIMENTO FOR TBABASTECIMENTO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  if (new.id is null) then
     new.id = gen_id(gen_id_abastecimento, 1);
END^

SET TERM ; ^

/* Definition for the `TG_BOMBA_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TG_BOMBA_ID FOR TBBOMBA
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  if (new.id is null) then
    new.id = gen_id(gen_id_bomba, 1);
END^

SET TERM ; ^

/* Definition for the `TG_FUNCIONARIO` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TG_FUNCIONARIO FOR TBFUNCIONARIO
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  if (new.id is null) then
     new.id = gen_id(gen_id_funcionario, 1);
END^

SET TERM ; ^

/* Definition for the `TG_TANQUE` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TG_TANQUE FOR TBTANQUE
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  if (new.id is null) then
     new.id = gen_id(gen_id_tanque, 1);
END^

SET TERM ; ^

/* Definition for the `RDB$ADMIN` role :  */

CREATE ROLE RDB$ADMIN;

GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBTANQUE TO SYSDBA WITH GRANT OPTION;
GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBBOMBA TO SYSDBA WITH GRANT OPTION;
GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBFUNCIONARIO TO SYSDBA WITH GRANT OPTION;
GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBABASTECIMENTO TO SYSDBA WITH GRANT OPTION;
GRANT SELECT, INSERT, DELETE, REFERENCES, UPDATE ON TBCONFIG TO SYSDBA WITH GRANT OPTION;

